### PR TITLE
Potentially Merging JonnyPower's improvements

### PR DESCRIPTION
**Pull request by QueenOfSquiggles**
I really like these changes and am definitely interested in merging them if possible. I will wait for @JonnyPower to confirm either approval or denial of this merge. (I won't merge without approval)

### CODE REVIEW

**Comment by QueenOfSquiggles** [comment]
Looks like CI is failing on Ubuntu due to `Diff in /home/runner/work/bevy_steamworks/bevy_steamworks/src/lib.rs:56:`
Perhaps I erroneously assumed the diffs were only github side? Or maybe this is a CI failure on my part. Windows and Mac seem to take this like champs. Not sure why

**Review by QueenOfSquiggles — COMMENTED** [review]
LGTM

**Comment by JonnyPower** [comment]
happy for you to merge but my main branch is not necessarily stable - I'm just adding stuff I need in the moment without extensive testing

**Review by JonnyPower — APPROVED** [review]

**Comment by QueenOfSquiggles** [comment]
I'm gonna do a funky little switcheroo to this and merge into a dev branch so I can hash out the issues with ubuntu/linux builds. Then I'll merge from that to main once I can get it stable (keeping main branch as stable as possible.) From there @JonnyPower if you want the stability fixes I make, feel free to do a PR and merge :heart:

**Pull request closed without merging**
