### PR TITLE
Rebasing to hourai

### PR DESCRIPTION
**Pull request by QueenOfSquiggles**

### CODE REVIEW

**Comment by QueenOfSquiggles** [comment]
Finally got it to merge into my own repo :sob: I worry I might have just spammed the base repo accidentally

**Comment by QueenOfSquiggles** [comment]
*Technically* nothing is actually changing, but it does clear up the "X commits behind" popup which I don't like

**Comment by xuesezhijian** [comment]
Hello! QueenOfSquiggles
I saw your mods a long time ago, and I decided to make a mod that would add my favorite bigwigs to my childhood easter eggs, so I hope you'll agree with me doing this

**Comment by QueenOfSquiggles** [comment]
> Hello! QueenOfSquiggles
> I saw your mods a long time ago, and I decided to make a mod that would add my favorite bigwigs to my childhood easter eggs, so I hope you'll agree with me doing this

Hey that sounds super cool. If that's what you wanna make, go for it! Have fun. Also I'd love to see it when its done so drop a link sometime ❤️

Though I gotta say there's better ways to message me lol

**Comment by xuesezhijian** [comment]
There is a better way to contact you, but I don't know and I can't find it. I can only look for your email on GitHub.ψ(｀∇´)ψ



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/08/2024 08:27 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [QueenOfSquiggles/bevy_steamworks] Rebasing to hourai (PR #9) |

Hello! QueenOfSquiggles
I saw your mods a long time ago, and I decided to make a mod that would add my favorite bigwigs to my childhood easter eggs, so I hope you'll agree with me doing this

Hey that sounds super cool. If that's what you wanna make, go for it! Have fun. Also I'd love to see it when its done so drop a link sometime ❤️

Though I gotta say there's better ways to message me lol

**Comment by QueenOfSquiggles** [comment]
> There is a better way to contact you, but I don't know and I can't find it. I can only look for your email on GitHub.ψ(｀∇´)ψ
> 
> 
> 
> ---- Replied Message ----
> | From | ***@***.***> |
> | Date | 10/08/2024 08:27 |
> | To | ***@***.***> |
> | Cc | ***@***.***>***@***.***> |
> | Subject | Re: [QueenOfSquiggles/bevy_steamworks] Rebasing to hourai (PR #9) |
> 
> Hello! QueenOfSquiggles
> I saw your mods a long time ago, and I decided to make a mod that would add my favorite bigwigs to my childhood easter eggs, so I hope you'll agree with me doing this
> 
> Hey that sounds super cool. If that's what you wanna make, go for it! Have fun. Also I'd love to see it when its done so drop a link sometime ❤️
> 
> Though I gotta say there's better ways to message me lol
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

I've got my contact info in the footer of my website (though I should check if my github links to my website, might have forgotten to do that)

https://queenofsquiggles.github.io/

**Comment by xuesezhijian** [comment]
I think I completely forgot about the jet lag.😂I still thought in the morning that you should be too busy to reply, but now I remember that there is still time difference.😓



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/08/2024 21:49 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [QueenOfSquiggles/bevy_steamworks] Rebasing to hourai (PR #9) |

There is a better way to contact you, but I don't know and I can't find it. I can only look for your email on GitHub.ψ(｀∇´)ψ

---- Replied Message ----
| From | @.> |
| Date | 10/08/2024 08:27 |
| To | @.> |
| Cc | @.>@.> |
| Subject | Re: [QueenOfSquiggles/bevy_steamworks] Rebasing to hourai (PR #9) |

Hello! QueenOfSquiggles
I saw your mods a long time ago, and I decided to make a mod that would add my favorite bigwigs to my childhood easter eggs, so I hope you'll agree with me doing this

Hey that sounds super cool. If that's what you wanna make, go for it! Have fun. Also I'd love to see it when its done so drop a link sometime ❤️

Though I gotta say there's better ways to message me lol

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: @.***>

I've got my contact info in the footer of my website (though I should check if my github links to my website, might have forgotten to do that)

https://queenofsquiggles.github.io/

**Comment by xuesezhijian** [comment]
Do you have an account in Weibo? We can talk in Weibo. It seems that international social software is not allowed in my country.😓



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/08/2024 21:49 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [QueenOfSquiggles/bevy_steamworks] Rebasing to hourai (PR #9) |

There is a better way to contact you, but I don't know and I can't find it. I can only look for your email on GitHub.ψ(｀∇´)ψ

---- Replied Message ----
| From | @.> |
| Date | 10/08/2024 08:27 |
| To | @.> |
| Cc | @.>@.> |
| Subject | Re: [QueenOfSquiggles/bevy_steamworks] Rebasing to hourai (PR #9) |

Hello! QueenOfSquiggles
I saw your mods a long time ago, and I decided to make a mod that would add my favorite bigwigs to my childhood easter eggs, so I hope you'll agree with me doing this

Hey that sounds super cool. If that's what you wanna make, go for it! Have fun. Also I'd love to see it when its done so drop a link sometime ❤️

Though I gotta say there's better ways to message me lol

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: @.***>

I've got my contact info in the footer of my website (though I should check if my github links to my website, might have forgotten to do that)

https://queenofsquiggles.github.io/

**Comment by QueenOfSquiggles** [comment]
I'd rather not add another social account, especially on a site that I can't really read :sob: (I can only really read English with any degree of proficiency)

But I do have an email if you have to contact me for something. Either way, best of luck!

**Comment by xuesezhijian** [comment]
Ok ~ _ ~, have a nice new day.



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/11/2024 21:16 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [QueenOfSquiggles/bevy_steamworks] Rebasing to hourai (PR #9) |

I'd rather not add another social account, especially on a site that I can't really read 😭 (I can only really read English with any degree of proficiency)

But I do have an email if you have to contact me for something. Either way, best of luck!

**Pull request merged**
